# Generated by Django 2.0.13 on 2020-05-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'catgories',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('tel', models.CharField(max_length=11, verbose_name='連絡先')),
                ('email', models.EmailField(max_length=254, verbose_name='Eメール')),
                ('body', models.TextField(verbose_name='本文')),
                ('reply', models.BooleanField(default=False, verbose_name='返信フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoryname', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inquiry.Category')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
            },
        ),
    ]
