# Generated by Django 2.0.13 on 2020-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='並び順'),
        ),
    ]
