# Generated by Django 2.0.13 on 2020-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('del_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('start_date', models.DateTimeField(verbose_name='公開日時')),
                ('end_date', models.DateTimeField(verbose_name='公開終了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
