# Generated by Django 2.0.13 on 2020-05-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='del_flg',
        ),
    ]
